import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MD-Accessories</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Image src='/images/MD.png' alt='MD' width={500} height={500} />
        <h1 className={styles.title}>Welcome to MD-Accessories !</h1>
      </main>
    </div>
  );
}
