import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MD-Accessories</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div className={styles.bg}>
          <Image
            src='/images/Background.png'
            layout='fill'
            objectFit='cover'
            quality={100}
            alt='Background'
          />
        </div>

        <Image src='/images/MD.png' alt='MD' width={500} height={500} />

        <Link href='/mainPage' passHref>
          <h1 className='title'> &gt; Enter here &lt; </h1>
        </Link>
      </main>
      <footer>
        <p className={styles.footer}>Powered by MD Accessories</p>
      </footer>
    </div>
  );
}
